package com.mycompany.movierater;
import java.util.*;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.*;
import javax.swing.event.*;

public class AppUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AppUI.class.getName());

    Movie[] movieDatabase;//our filled movie array
    DefaultListModel<Movie> ratedListModel = new DefaultListModel(); //this is so we can edit the dumb ass JList, because JList is read only
    JList<Movie> ratedMovies = new JList<>(ratedListModel); //create the JList, we need it so the Jscroll panel can display the movies
    
    /**
     * Creates new form AppUI
     */
    public AppUI(Movie[] movieDatabase) { //CONSTRUCTORRRRRR
        this.movieDatabase = movieDatabase; //gets the filled database
        initComponents();
        jScrollPane1.setViewportView(ratedMovies); //shows the list :0
    }
    
    public void addMovie() {
        String movieTitle = jTextField1.getText().trim(); //gets the entered title and removes any unneccecery spaces

        if (movieTitle.isEmpty()) {
            return; //if its empty
        }
        
        Movie foundMovie = null; //variable for the movie we should find but havent found yet
        
        for(int i = 0; i < movieDatabase.length; i++) { //searching for mathcing titles
            if (movieTitle.equalsIgnoreCase(movieDatabase[i].getTitle())) { //ignores all upper and lowercase and looks if the titles match
                foundMovie = movieDatabase[i]; //assign a movie to the foundMovie
                break;
            }
        }
        
        if (foundMovie == null) { //if we didnt find the movie in the database
            showMessageDialog(null, "Movie not found: " + movieTitle);
        } else if (ratedListModel.contains(foundMovie)) { //if movie is already in the rated list
            showMessageDialog(null, "Movie already in list");
        } else { //if all is good, then we add the newly found movie to our rated list
            ratedListModel.addElement(foundMovie);
            jTextField1.setText("");
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setText("Title here");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jButton1.setText("Add");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        addMovie();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        addMovie();
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
